### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by jcschmidig** [codechips/svelte-snowpack-testdrive#1]
"npm run build" doesn't work:

  mount:web_modules.......[DONE] mount $WEB_MODULES --to /web_modules
  mount:public............[DONE] mount public --to /
  mount:src...............[DONE] mount src --to /_dist_
  build:css...............[DONE] postcss
  build:js,jsx,ts,tsx.....[DONE] (default) esbuild
  build:svelte............[DONE] (plugin) @snowpack/plugin-svelte
  bundle:*................[FAIL] (plugin) @snowpack/plugin-webpack

▼ bundle:*

  TypeError: Cannot read property 'baseUrl' of undefined

▼ Result

  ⚠️  Finished, with errors.

>> Tried on npm 12.14.0 and 14.2.0

**Comment by jcschmidig** [comment]
It works with snowpack version 2.5.2 instead of 2.0.3!

**Comment by codechips** [comment]
Great! Closing it then :+1:
